name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"  # toutes les 12h
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake
        uses: Platane/snk@master
        with:
          github_user_name: theotimeqrt
          outputs: dist/github-contribution-grid-snake.svg

      - name: push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
